files: '^application/'
fail_fast: true

repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.7

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.4.0
      hooks:
        -   id: trailing-whitespace
        -   id: check-executables-have-shebangs
        -   id: end-of-file-fixer
        -   id: debug-statements
        -   id: check-json
        -   id: check-yaml
        -   id: check-merge-conflict
